#!/usr/bin/env bash
# servers are the piece of software generating and serving HTML pages
# install and configure Nginx on an Ubuntu server

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -s reload
