#!/usr/bin/env bash
# A script to install and configure Nginx on an Ubuntu server

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

echo -e "\nSetting up.\n"

# Starting Nginx service
sudo service nginx start

# Allowing Nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Backup default index
sudo mv /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restarting Nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
