#!/usr/bin/env bash
# nginx likes port 80

# Update package lists
sudo apt-get update -y

# Install nginx
sudo apt-get install -y nginx

# Enable and start nginx service
sudo systemctl enable nginx
sudo systemctl start nginx
