#!/usr/bin/env bash

# Handle SIGTERM
handle_sigterm()
{
	echo "I hate the kill command"
}

# Handle SIGINT
handle_sigint()
{
	echo "Y U no love me?!"
}

# Handle SIGQUIT
handle_sigquit()
{
	echo "Deleting PID file and terminating script"
	rm /var/run/myscript.pid
	exit 0
}

# Trap signals and associate them with respective functions
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

# Get PID and write it to PID file
echo $$ > /var/run/myscript.pid

# Display messages indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
