#!/usr/bin/env bash

# stops 4-to_infinity_and_beyond process w/o kill

# process ID (PID) of the script
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -z "$pid" ]; then
    echo "Process not found."
else
    # Send a termination signal to the process
    kill -15 "$pid"
fi
