#!/usr/bin/env bash

# Find the process ID (PID) of the script using ps, grep, and awk
pid=$(ps aux | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')

if [ -z "$pid" ]; then
    echo "Process not found."
else
    # Send a termination signal to the process
    # You can use any signal you want, SIGTERM (15) is a common choice
    kill -15 "$pid"
    echo "Process terminated."
fi
