#!/usr/bin/env bash

# Display "Best School" 10 times using a while loop

counter=0

while [ $counter -lt 10 ]
do
    if [ $counter -eq 8 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    
    ((counter++))
done
