#!/usr/bin/env bash
# Display "Best School" 1-10 but special messages for 4 & 8

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    
    ((counter++))
done
